/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Validation error",
                         *         "details": {
                         *           "fieldErrors": {
                         *             "email": [
                         *               "Invalid email"
                         *             ]
                         *           }
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "CONFLICT",
                         *         "message": "Resource already exists",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login (access token + refresh cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Validation error",
                         *         "details": {
                         *           "fieldErrors": {
                         *             "email": [
                         *               "Invalid email"
                         *             ]
                         *           }
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token (using refreshToken cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (clears refresh cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user (access token) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/canvases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List canvases */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListCanvasesResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /** Create canvas */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCanvasRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateCanvasResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Validation error",
                         *         "details": {
                         *           "fieldErrors": {
                         *             "email": [
                         *               "Invalid email"
                         *             ]
                         *           }
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/canvases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get canvas with blocks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetCanvasWithBlocksResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete canvas */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "FORBIDDEN",
                         *         "message": "You do not have access to this resource",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update canvas */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateCanvasRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateCanvasResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Validation error",
                         *         "details": {
                         *           "fieldErrors": {
                         *             "email": [
                         *               "Invalid email"
                         *             ]
                         *           }
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/canvases/{id}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create block in canvas */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateBlockRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BlockResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Validation error",
                         *         "details": {
                         *           "fieldErrors": {
                         *             "email": [
                         *               "Invalid email"
                         *             ]
                         *           }
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        /** Bulk update blocks in canvas */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BulkUpdateBlocksRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BulkUpdateBlocksResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Validation error",
                         *         "details": {
                         *           "fieldErrors": {
                         *             "email": [
                         *               "Invalid email"
                         *             ]
                         *           }
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/blocks/{blockId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a block */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    blockId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a block */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    blockId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateBlockRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BlockResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Validation error",
                         *         "details": {
                         *           "fieldErrors": {
                         *             "email": [
                         *               "Invalid email"
                         *             ]
                         *           }
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/public/canvases/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public canvas with blocks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetCanvasWithBlocksResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterResponse: {
            /** @example User registered */
            message: string;
            data: components["schemas"]["UserPublic"];
        };
        UserPublic: {
            /** @example ckw... */
            id: string;
            /**
             * Format: email
             * @example test@example.com
             */
            email: string;
            /** @example Seoudy */
            name: string;
            /** @example 2026-01-27T10:00:00.000Z */
            createdAt: string;
        };
        ErrorEnvelope: {
            error: {
                /** @enum {string} */
                code: "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "INTERNAL_ERROR";
                message: string;
                details?: unknown;
            };
        };
        RegisterRequest: {
            /**
             * Format: email
             * @example test@example.com
             */
            email: string;
            /** @example 12345678 */
            password: string;
            /** @example Seoudy */
            name: string;
        };
        LoginResponse: {
            /** @example User logged in */
            message: string;
            data: {
                /** @example eyJ... */
                accessToken: string;
                user: components["schemas"]["UserPublic"];
            };
        };
        LoginRequest: {
            /**
             * Format: email
             * @example test@example.com
             */
            email: string;
            /** @example 12345678 */
            password: string;
        };
        RefreshResponse: {
            /** @example Token refreshed */
            message: string;
            data: {
                /** @example eyJ... */
                accessToken: string;
            };
        };
        LogoutResponse: {
            /** @example Logged out */
            message: string;
        };
        MeResponse: {
            data: components["schemas"]["UserPublic"];
        };
        CreateCanvasResponse: {
            /** @example Canvas created */
            message: string;
            data: components["schemas"]["Canvas"];
        };
        Canvas: {
            id: string;
            title: string;
            description: string | null;
            isPublic: boolean;
            publicToken: string | null;
            ownerId: string;
            createdAt: string;
            updatedAt: string;
        };
        CreateCanvasRequest: {
            /** @example My first canvas */
            title: string;
            /** @example test */
            description?: string | null;
            /** @example false */
            isPublic?: boolean;
        };
        ListCanvasesResponse: {
            data: {
                items: components["schemas"]["Canvas"][];
                page: number;
                limit: number;
                total: number;
                totalPages: number;
            };
        };
        GetCanvasWithBlocksResponse: {
            data: {
                canvas: components["schemas"]["Canvas"];
                blocks: components["schemas"]["Block"][];
            };
        };
        Block: {
            id: string;
            canvasId: string;
            type: string;
            x: number;
            y: number;
            w: number;
            h: number;
            content?: unknown;
            createdAt: string;
            updatedAt: string;
        };
        UpdateCanvasResponse: {
            /** @example Canvas updated */
            message: string;
            data: components["schemas"]["Canvas"];
        };
        UpdateCanvasRequest: {
            /** @example New title */
            title?: string;
            /** @example null */
            description?: string | null;
            /** @example true */
            isPublic?: boolean;
        };
        BlockResponse: {
            message: string;
            data: components["schemas"]["Block"];
        };
        CreateBlockRequest: {
            /** @example text */
            type: string;
            /** @example 100 */
            x: number;
            /** @example 200 */
            y: number;
            /** @example 320 */
            w: number;
            /** @example 120 */
            h: number;
            /**
             * @example {
             *       "text": "Hello canvas"
             *     }
             */
            content?: unknown;
        };
        BulkUpdateBlocksResponse: {
            message: string;
            data: {
                blocks: components["schemas"]["Block"][];
            };
        };
        BulkUpdateBlocksRequest: {
            updates: {
                id: string;
                patch: components["schemas"]["UpdateBlockRequest"];
            }[];
        };
        UpdateBlockRequest: {
            x?: number;
            y?: number;
            w?: number;
            h?: number;
            content?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
