/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Validation error",
                         *         "details": {
                         *           "fieldErrors": {
                         *             "email": [
                         *               "Invalid email"
                         *             ]
                         *           }
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "CONFLICT",
                         *         "message": "Resource already exists",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login (access token + refresh cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Validation error",
                         *         "details": {
                         *           "fieldErrors": {
                         *             "email": [
                         *               "Invalid email"
                         *             ]
                         *           }
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token (using refreshToken cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (clears refresh cookie) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user (access token) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListDocumentsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /** Create document */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateDocumentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateDocumentResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Validation error",
                         *         "details": {
                         *           "fieldErrors": {
                         *             "email": [
                         *               "Invalid email"
                         *             ]
                         *           }
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get document (snapshot + meta) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "FORBIDDEN",
                         *         "message": "You do not have access to this resource",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        /** Update document snapshot (with revision check) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateDocumentSnapshotRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateSnapshotResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Conflict (revision mismatch) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        post?: never;
        /** Delete document */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "FORBIDDEN",
                         *         "message": "You do not have access to this resource",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update document metadata */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateDocumentMetadataRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateDocumentMetadataResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Validation error",
                         *         "details": {
                         *           "fieldErrors": {
                         *             "email": [
                         *               "Invalid email"
                         *             ]
                         *           }
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Invalid credentials",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/public/documents/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public document (snapshot + meta) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["DocumentResponse"];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Resource not found",
                         *         "details": null
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterResponse: {
            /** @example User registered */
            message: string;
            data: components["schemas"]["UserPublic"];
        };
        UserPublic: {
            /** @example ckw... */
            id: string;
            /**
             * Format: email
             * @example test@example.com
             */
            email: string;
            /** @example Seoudy */
            name: string;
            /** @example 2026-01-27T10:00:00.000Z */
            createdAt: string;
        };
        ErrorEnvelope: {
            error: {
                /** @enum {string} */
                code: "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "INTERNAL_ERROR";
                message: string;
                details?: unknown;
            };
        };
        RegisterRequest: {
            /**
             * Format: email
             * @example test@example.com
             */
            email: string;
            /** @example 12345678 */
            password: string;
            /** @example Seoudy */
            name: string;
        };
        LoginResponse: {
            /** @example User logged in */
            message: string;
            data: {
                /** @example eyJ... */
                accessToken: string;
                user: components["schemas"]["UserPublic"];
            };
        };
        LoginRequest: {
            /**
             * Format: email
             * @example test@example.com
             */
            email: string;
            /** @example 12345678 */
            password: string;
        };
        RefreshResponse: {
            /** @example Token refreshed */
            message: string;
            data: {
                /** @example eyJ... */
                accessToken: string;
            };
        };
        LogoutResponse: {
            /** @example Logged out */
            message: string;
        };
        MeResponse: {
            data: components["schemas"]["UserPublic"];
        };
        ListDocumentsResponse: {
            data: {
                items: components["schemas"]["DocumentMeta"][];
                page: number;
                limit: number;
                total: number;
                totalPages: number;
            };
        };
        DocumentMeta: {
            id: string;
            title: string;
            description: string | null;
            isPublic: boolean;
            publicToken: string | null;
            ownerId?: string;
            createdAt: string;
            updatedAt: string;
        };
        CreateDocumentResponse: {
            /** @example Document created */
            message: string;
            data: components["schemas"]["DocumentMeta"];
        };
        CreateDocumentRequest: {
            /** @example My document */
            title: string;
            description?: string | null;
            /** @default false */
            isPublic: boolean;
        };
        DocumentResponse: {
            id: string;
            title: string;
            description: string | null;
            isPublic: boolean;
            revision: number;
            data?: unknown;
        };
        UpdateDocumentMetadataResponse: {
            /** @example Document updated */
            message: string;
            data: components["schemas"]["DocumentMeta"];
        };
        UpdateDocumentMetadataRequest: {
            title?: string;
            description?: string | null;
            isPublic?: boolean;
        };
        UpdateSnapshotResponse: {
            revision: number;
            savedAt: string;
        };
        UpdateDocumentSnapshotRequest: {
            baseRevision: number;
            data?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
