/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SignupRouteImport } from './../routes/signup'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as ForbiddenRouteImport } from './../routes/forbidden'
import { Route as EditorRouteImport } from './../routes/editor'
import { Route as DashboardRouteImport } from './../routes/dashboard'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as EditorIndexRouteImport } from './../routes/editor.index'
import { Route as EditorDocumentIdRouteImport } from './../routes/editor.$documentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorRoute,
} as any)
const EditorDocumentIdRoute = EditorDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => EditorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/editor/$documentId': typeof EditorDocumentIdRoute
  '/editor/': typeof EditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/editor/$documentId': typeof EditorDocumentIdRoute
  '/editor': typeof EditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/editor/$documentId': typeof EditorDocumentIdRoute
  '/editor/': typeof EditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/editor'
    | '/forbidden'
    | '/login'
    | '/signup'
    | '/editor/$documentId'
    | '/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forbidden'
    | '/login'
    | '/signup'
    | '/editor/$documentId'
    | '/editor'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/editor'
    | '/forbidden'
    | '/login'
    | '/signup'
    | '/editor/$documentId'
    | '/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/$documentId': {
      id: '/editor/$documentId'
      path: '/$documentId'
      fullPath: '/editor/$documentId'
      preLoaderRoute: typeof EditorDocumentIdRouteImport
      parentRoute: typeof EditorRoute
    }
  }
}

interface EditorRouteChildren {
  EditorDocumentIdRoute: typeof EditorDocumentIdRoute
  EditorIndexRoute: typeof EditorIndexRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorDocumentIdRoute: EditorDocumentIdRoute,
  EditorIndexRoute: EditorIndexRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
